#!/usr/bin/env node
/**
 * Generates `lib/geo/states.generated.ts` from the latest source snapshot.
 *
 *   node scripts/geo/build-states.mjs
 *
 * States are the one half of the geography this project can verify without an
 * owner action: LGD serves the state/UT selector without a CAPTCHA, so the 36
 * codes below are authoritative and complete (28 states + 8 UTs). Districts
 * are not generated here — see docs/districts/AUDIT.md for why, and
 * scripts/geo/ingest-lgd.mjs for the script that will build them.
 *
 * Generated rather than hand-written so the codes cannot drift from the
 * snapshot they came from, and so a re-fetch shows up as a reviewable diff.
 * Idempotent: running it twice with the same snapshot produces byte-identical
 * output.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const SNAPSHOT = path.join(ROOT, "data", "geo", "snapshots", "latest.json");
const OUT = path.join(ROOT, "lib", "geo", "states.generated.ts");

/** URL-safe slug from an official name. Deterministic, no transliteration. */
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const snapshot = JSON.parse(await readFile(SNAPSHOT, "utf8"));

if (snapshot.stateSource !== "lgd-authoritative") {
  throw new Error(
    `refusing to generate: snapshot stateSource is "${snapshot.stateSource}", expected "lgd-authoritative"`
  );
}

const states = [...snapshot.states].sort((a, b) => a.name.localeCompare(b.name));

const seen = new Set();
for (const s of states) {
  const slug = slugify(s.name);
  if (seen.has(slug)) throw new Error(`duplicate state slug: ${slug}`);
  seen.add(slug);
}

const rows = states
  .map(
    (s) =>
      `  { lgdStateCode: ${s.lgdStateCode}, name: ${JSON.stringify(s.name)}, slug: ${JSON.stringify(
        slugify(s.name)
      )} },`
  )
  .join("\n");

const body = `// GENERATED by scripts/geo/build-states.mjs — do not edit by hand.
// Source: ${snapshot.sources.states.url}
// Publisher: ${snapshot.sources.states.publisher}
// Licence: ${snapshot.sources.states.licence}
// Retrieved: ${snapshot.retrievedAt}
// Snapshot checksum: ${snapshot.sources.states.checksum}

export type StateRecord = {
  /** Official LGD state/UT code — the stable key, never the name. */
  lgdStateCode: number;
  /** Official name exactly as LGD publishes it. */
  name: string;
  /** URL segment. Stable once published; renaming one is a migration. */
  slug: string;
};

/** All ${states.length} states and union territories, by LGD code. */
export const STATES: readonly StateRecord[] = [
${rows}
];

export function getStateByCode(code: number): StateRecord | undefined {
  return STATES.find((s) => s.lgdStateCode === code);
}

export function getStateBySlug(slug: string): StateRecord | undefined {
  return STATES.find((s) => s.slug === slug);
}
`;

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, body);
console.log(`wrote ${path.relative(ROOT, OUT)} — ${states.length} states/UTs`);
