// GENERATED by scripts/geo/build-states.mjs — do not edit by hand.
// Source: https://lgdirectory.gov.in/globalviewdistrictforcitizen.do
// Publisher: Local Government Directory (LGD), Ministry of Panchayati Raj, Government of India
// Licence: Government Open Data Licence – India (GODL)
// Retrieved: 2026-09-23T13:24:59.823Z
// Snapshot checksum: 23f6964159d9f9d19be22a5db7791cc7138f17ad12dbefb523f283114360f5f7

export type StateRecord = {
  /** Official LGD state/UT code — the stable key, never the name. */
  lgdStateCode: number;
  /** Official name exactly as LGD publishes it. */
  name: string;
  /** URL segment. Stable once published; renaming one is a migration. */
  slug: string;
};

/** All 36 states and union territories, by LGD code. */
export const STATES: readonly StateRecord[] = [
  { lgdStateCode: 35, name: "Andaman And Nicobar Islands", slug: "andaman-and-nicobar-islands" },
  { lgdStateCode: 28, name: "Andhra Pradesh", slug: "andhra-pradesh" },
  { lgdStateCode: 12, name: "Arunachal Pradesh", slug: "arunachal-pradesh" },
  { lgdStateCode: 18, name: "Assam", slug: "assam" },
  { lgdStateCode: 10, name: "Bihar", slug: "bihar" },
  { lgdStateCode: 4, name: "Chandigarh", slug: "chandigarh" },
  { lgdStateCode: 22, name: "Chhattisgarh", slug: "chhattisgarh" },
  { lgdStateCode: 7, name: "Delhi", slug: "delhi" },
  { lgdStateCode: 30, name: "Goa", slug: "goa" },
  { lgdStateCode: 24, name: "Gujarat", slug: "gujarat" },
  { lgdStateCode: 6, name: "Haryana", slug: "haryana" },
  { lgdStateCode: 2, name: "Himachal Pradesh", slug: "himachal-pradesh" },
  { lgdStateCode: 1, name: "Jammu And Kashmir", slug: "jammu-and-kashmir" },
  { lgdStateCode: 20, name: "Jharkhand", slug: "jharkhand" },
  { lgdStateCode: 29, name: "Karnataka", slug: "karnataka" },
  { lgdStateCode: 32, name: "Kerala", slug: "kerala" },
  { lgdStateCode: 37, name: "Ladakh", slug: "ladakh" },
  { lgdStateCode: 31, name: "Lakshadweep", slug: "lakshadweep" },
  { lgdStateCode: 23, name: "Madhya Pradesh", slug: "madhya-pradesh" },
  { lgdStateCode: 27, name: "Maharashtra", slug: "maharashtra" },
  { lgdStateCode: 14, name: "Manipur", slug: "manipur" },
  { lgdStateCode: 17, name: "Meghalaya", slug: "meghalaya" },
  { lgdStateCode: 15, name: "Mizoram", slug: "mizoram" },
  { lgdStateCode: 13, name: "Nagaland", slug: "nagaland" },
  { lgdStateCode: 21, name: "Odisha", slug: "odisha" },
  { lgdStateCode: 34, name: "Puducherry", slug: "puducherry" },
  { lgdStateCode: 3, name: "Punjab", slug: "punjab" },
  { lgdStateCode: 8, name: "Rajasthan", slug: "rajasthan" },
  { lgdStateCode: 11, name: "Sikkim", slug: "sikkim" },
  { lgdStateCode: 33, name: "Tamil Nadu", slug: "tamil-nadu" },
  { lgdStateCode: 36, name: "Telangana", slug: "telangana" },
  { lgdStateCode: 38, name: "The Dadra And Nagar Haveli And Daman And Diu", slug: "the-dadra-and-nagar-haveli-and-daman-and-diu" },
  { lgdStateCode: 16, name: "Tripura", slug: "tripura" },
  { lgdStateCode: 9, name: "Uttar Pradesh", slug: "uttar-pradesh" },
  { lgdStateCode: 5, name: "Uttarakhand", slug: "uttarakhand" },
  { lgdStateCode: 19, name: "West Bengal", slug: "west-bengal" },
];

export function getStateByCode(code: number): StateRecord | undefined {
  return STATES.find((s) => s.lgdStateCode === code);
}

export function getStateBySlug(slug: string): StateRecord | undefined {
  return STATES.find((s) => s.slug === slug);
}
